# Generated by Django 4.1.13 on 2024-01-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial')
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='contenido',
        ),
        migrations.AddField(
            model_name='topico',
            name='informacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topico',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
